name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.20", "1.21", "1.22", "1.23"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Create bin directory
        run: mkdir -p bin

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21" # Using stable version for releases

      - name: Create bin directory
        run: mkdir -p bin

      - name: Build all platforms
        run: make build-all

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/go-git-swap-darwin-amd64
            bin/go-git-swap-darwin-arm64
            bin/go-git-swap-linux-amd64
            bin/go-git-swap-linux-arm64
